---
- name: Disable third party resources
  lineinfile:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^    disableThirdPartyRequests"
    line: "    disableThirdPartyRequests: true,"
    state: present

- name: Set the Jitsi Meet hostname
  replace:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^(.*')localhost('.*)"
    replace: "\\1{{ jitsi_meet_hostname }}\\2"

- name: Symlink Jitsi config by domain name.
  file:
    path: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    state: link
    src: /etc/jitsi/meet/localhost-config.js
