---
- name: Disable third party resources
  lineinfile:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^    disableThirdPartyRequests"
    line: "    disableThirdPartyRequests: true,"
    state: present

- name: Set the Jitsi Meet hostname
  replace:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^(.*)localhost(.*)"
    replace: "\\1{{ jitsi_meet_server_name }}\\2"

- name: Configure Prosody.
  template:
    src: prosody_config.j2
    dest: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    mode: "0644"
  notify: restart prosody

- name: Set hostname in Jicofo config.
  lineinfile:
    dest: /etc/jitsi/jicofo/config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^JICOFO_HOST='
      line: "JICOFO_HOST={{ jitsi_meet_server_name }}"
    - regexp: '^JICOFO_HOSTNAME='
      line: "JICOFO_HOSTNAME={{ jitsi_meet_server_name }}"
    - regexp: '^JICOFO_AUTH_DOMAIN='
      line: "JICOFO_AUTH_DOMAIN=auth.{{ jitsi_meet_server_name }}"
  notify: restart jicofo

- name: Symlink Prosody config by domain name.
  file:
    path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    state: link
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
  notify: restart prosody

- name: Symlink Jitsi config by domain name.
  file:
    path: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    state: link
    src: /etc/jitsi/meet/localhost-config.js
