---
- name: Disable third party resources
  lineinfile:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^    disableThirdPartyRequests"
    line: "    disableThirdPartyRequests: true,"
    state: present

- name: Set the Jitsi Meet hostname
  replace:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^(.*)localhost(.*)"
    replace: "\\1{{ jitsi_meet_server_name }}\\2"

- name: Configure Prosody.
  template:
    src: prosody_config.j2
    dest: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    mode: "0644"
  notify: restart prosody

- name: Symlink Prosody config by domain name.
  file:
    path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    state: link
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
  notify: restart prosody

- name: Symlink Jitsi config by domain name.
  file:
    path: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    state: link
    src: /etc/jitsi/meet/localhost-config.js
