---
- name: Copy Nginx config for Jitsi Meet domain.
  template:
    dest: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
    src: jitsi_meet_nginx.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx

- name: Deactivate default Nginx sites.
  file:
    path: /etc/nginx/sites-enabled/{{ item }}
    state: absent
  with_items:
    - default
    - localhost.conf
  notify: restart nginx

- name: Activate custom Jitsi Meet Nginx site.
  file:
    path: "/etc/nginx/sites-enabled/{{ jitsi_meet_server_name }}.conf"
    src: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
    state: link
  notify: restart nginx
