---
- name: Install ufw package.
  apt:
    name: ufw
    state: present

- name: Specify allowed ports in firewall config.
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443
    - 4443
  notify: reload ufw

- name: Open UDP port 10000 for jitsi-videobridge
  ufw:
    rule: allow
    port: 10000
    proto: udp
  notify: reload ufw

- name: Ensure UFW is running.
  ufw:
    name: ufw
    state: enabled
