version: 2
jobs:
  build:
    working_directory: /root/pressfreedom
    docker:
      - image: msheiny/pressfreedomci:latest
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Run molecule and testinfra tests
          command: make ci-go
