---
- name: Test jitsi-meet role (stable repo)
  hosts: jitsi-meet-stable,jitsi-meet-unstable
  roles:
    - role: ../ansible-role-jitsi-meet
      jitsi_meet_use_nightly_apt_repo: "{{ true if inventory_hostname.endswith('unstable') else false }}"
